In [1]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x * y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2, 5])
x.shape

torch.Size([2, 5])

In [7]:
y = torch.rand([2, 5])
y

tensor([[0.0861, 0.8626, 0.6100, 0.6745, 0.4492],
        [0.4329, 0.5358, 0.8662, 0.9805, 0.8136]])

In [8]:
y.view([1, 10])
y

tensor([[0.0861, 0.8626, 0.6100, 0.6745, 0.4492],
        [0.4329, 0.5358, 0.8662, 0.9805, 0.8136]])